### ISSUE TITLE
Event handling not cross-platform compatible and TAB not recognized

### ISSUE THREAD

**Issue by Patrikgyllvin** [lunduniversity/introprog-scalalib#11]
Key event handling is not cross-platform compatible as noted in lunduniversity/introprog#491. See also #1 which is related.

I have a working fix for above issues tested on macOS and Linux, see comment https://github.com/lunduniversity/introprog/issues/491#issuecomment-705213220. Could use help with testing on Windows.

Another issue persists which is that `TAB` key strokes are not recognized by introprog. From what I can gather this seems related to the Focus Subsystem of Swing, where `TAB` and `Shift-TAB` will cycle the focus forward or backwards. This would need to be disabled for the event handler to recognize the key strokes.

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812 Perhaps you can assist @Patrikgyllvin with testing on Windows when he has a (almost) PR ready?

**Comment by Patrikgyllvin** [comment]
My fork of this repo now contains commits with fixes for these issues, tested on macOS. Again I will need to test on Linux, and assistance with testing on Windows before PR would be appreciated.

**Comment by Patrikgyllvin** [comment]
This has now been tested on Linux and Windows successfully. There is a difference in behavior on the Windows & OpenJDK system I tested where the `Alt Gr` key fires both `Ctrl` and `Alt` key events. This appears to be due to Windows' or the JDK's handling of this event and it might not be possible to fix. Is this behavior acceptable, in which case this seems PR ready, or should we look more into it?

**Comment by jos-rosenqvist-3812** [comment]
I'm familiar with that behavior occurring on Windows outside of the JDK. It shouldn't be a problem, as there isn't anything we need to use AltGr for in the course.

**Comment by bjornregnell** [comment]
I guess the only (reasonable) way to get consistent x-platform behaviour is to use jline, but that creates another dependency and I'd rather have introprog-scalalib without any other dependencies, and also since jline risk clashing with another version that sbt/scala may use now or in the future. So go ahead and PR when all major platforms have been tested sans AltGrrrrrr :)

**Comment by bjornregnell** [comment]
Include this number #11 and also the issue number #1 on the Delete key if that is also fixed in the commit message and these issues will be auto-closed when merged.
