### ISSUE TITLE
use github actions for CI

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog-scalalib#19]
@fritjof-b If you like, you are very welcome to add github actions with build badge here. use `sbt compile` as we have no tests yet...

**Comment by fritjof-b** [comment]
Doing it after I get home from work.

**Comment by bjornregnell** [comment]
I tried to assign you but couldn't. Maybe you need to belong to a group of the org or something. I'll look in to that.

**Comment by bjornregnell** [comment]
Now I could assign you! I guess it is perhaps because you now have made a comment.
