### ISSUE TITLE
Links to source code is missing from API

### ISSUE THREAD

**Issue by IndigoWilke** [lunduniversity/introprog-scalalib#28]
In exercise 7 chap 4 we're to look at the source code for TestPixelWindow however there is no link to the source code at https://fileadmin.cs.lth.se/pgk/api/api/introprog/examples/TestPixelWindow$.html
 Nor are there links for any other source code. Björn noted that this is likely to be due to the new scaladoc for Scala 3
and thinks a new option is needed, see link: https://docs.scala-lang.org/scala3/guides/scaladoc/settings.html

**Comment by Husenap** [comment]
This issue can now be closed as it has been fixed.
