### ISSUE TITLE
7.1.36 repl contains typos

### ISSUE THREAD

**Issue by IndigoWilke** [lunduniversity/introprog-scalalib#35]
The example where the repl is shown in chapter 7 part 1 subpart 36 needs some fixing 
As it is now this is how it looks:

scala> type Pt = (Int, Int)
scala> def distToOrigo(pt: Pt): Int = math.hypot(pt._1, pt._2)
scala> type Pts = Vector[Pt]
scala> def firstPt(pts: Pts): Pt = pts.head
scala> val xs: Pde3,3))
scala> firstPt(xde
res0: Pt = (1,1)de

Last three lines needs some fixing

**Comment by bjornregnell** [comment]
this regards https://github.com/lunduniversity/introprog/issues

fixing this there by this commit: https://github.com/lunduniversity/introprog/commit/c6fa62b7914373f980baff474bdbac3a30a4d421
