### ISSUE TITLE
Lack of documentation / information for how BlockWindow works?

### ISSUE THREAD

**Issue by dixine55** [lunduniversity/introprog-scalalib#44]
During the SnakeLab there's some confusion regarding how drawBlock() in BlockWindow works.

This is partly due to the fact that if you instantiate a BlockWindow class in REPL (which students repeatedly are told to play around in) and then use the drawBlock() function, nothing happens.

A solution would be to perhaps have a very primitive code that shows the functionality in a working state, where students can play around as REPL doesn't provide that functionality and still not give away too much, so there's still learning potential.

For example the code found here could possibly help; https://github.com/dixine55/BlockWindow-functionality

Another solution would be to inside of the introprog Documentation mention that drawBlock only works inside of a gameLoop, and specify what that is and how to initiate one.

**Comment by bjornregnell** [comment]
Now here: https://github.com/lunduniversity/introprog-scalalib/blob/master/src/main/scala/introprog/examples/TestBlockGame.scala#L72

TODO: add explanation in docs of gameLoop

**Comment by bjornregnell** [comment]
Fixed in https://github.com/lunduniversity/introprog-scalalib/commit/74a56caf0677390b1baa8f27b96962979db997b0
